In [1]:
import pandas as pd
import numpy as np

In [2]:
path = '/Users/josia/Desktop/Python/NSSL Internship/'

In [3]:
data = pd.read_csv(path + 'Data/P2/5s_AVG_P2.csv')
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,Altitude,GPS Speed,Meso Lat,Meso Lon
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679903,-91.374930
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679969,-91.374551
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680034,-91.374171
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680099,-91.373792
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680164,-91.373413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,47.74,27.57,33.227261,-90.257489
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,47.78,27.57,33.227391,-90.257533
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,47.80,27.57,33.227521,-90.257576
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227651,-90.257619
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227781,-90.257663

In [4]:
# convert to radians

In [5]:
data['P2 Lat Rad'] = np.radians(np.array(data['Latitude']))
data['P2 Lon Rad'] = np.radians(data['Longitude'])
data['Meso Lat Rad'] = np.radians(data['Meso Lat'])
data['Meso Lon Rad'] = np.radians(data['Meso Lon'])
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,Altitude,GPS Speed,Meso Lat,Meso Lon,P2 Lat Rad,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679903,-91.374930,NaN,NaN,0.570372,-1.594793
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679969,-91.374551,NaN,NaN,0.570373,-1.594787
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680034,-91.374171,NaN,NaN,0.570374,-1.594780
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680099,-91.373792,NaN,NaN,0.570375,-1.594774
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680164,-91.373413,NaN,NaN,0.570376,-1.594767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,47.74,27.57,33.227261,-90.257489,0.577952,-1.586082,0.579925,-1.575290
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,47.78,27.57,33.227391,-90.257533,0.577955,-1.586080,0.579927,-1.575291
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,47.80,27.57,33.227521,-90.257576,0.577959,-1.586078,0.579930,-1.575292
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227651,-90.257619,0.577962,-1.586075,0.579932,-1.575293
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227781,-90.257663,0.577968,-1.586073,0.579934,-1.575293

In [6]:
# Haversine Formula

In [7]:
data['a'] = ((np.sin((data['P2 Lat Rad'] - data['Meso Lat Rad']) / 2))**2 
             + np.cos(data['Meso Lat Rad'])*np.cos(data['P2 Lat Rad'])*(np.sin((data['P2 Lon Rad'] - data['Meso Lon Rad'])/2))**2)
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,Altitude,GPS Speed,Meso Lat,Meso Lon,P2 Lat Rad,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad,a
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679903,-91.374930,NaN,NaN,0.570372,-1.594793,NaN
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679969,-91.374551,NaN,NaN,0.570373,-1.594787,NaN
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680034,-91.374171,NaN,NaN,0.570374,-1.594780,NaN
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680099,-91.373792,NaN,NaN,0.570375,-1.594774,NaN
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680164,-91.373413,NaN,NaN,0.570376,-1.594767,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,47.74,27.57,33.227261,-90.257489,0.577952,-1.586082,0.579925,-1.575290,0.000021
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,47.78,27.57,33.227391,-90.257533,0.577955,-1.586080,0.579927,-1.575291,0.000021
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,47.80,27.57,33.227521,-90.257576,0.577959,-1.586078,0.579930,-1.575292,0.000021
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227651,-90.257619,0.577962,-1.586075,0.579932,-1.575293,0.000021
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227781,-90.257663,0.577968,-1.586073,0.579934,-1.575293,0.000021

In [8]:
data['c'] = 2*np.arctan2(np.sqrt(data['a']), np.sqrt((1 - data['a'])))
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,Altitude,GPS Speed,Meso Lat,Meso Lon,P2 Lat Rad,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad,a,c
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679903,-91.374930,NaN,NaN,0.570372,-1.594793,NaN,NaN
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.679969,-91.374551,NaN,NaN,0.570373,-1.594787,NaN,NaN
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680034,-91.374171,NaN,NaN,0.570374,-1.594780,NaN,NaN
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680099,-91.373792,NaN,NaN,0.570375,-1.594774,NaN,NaN
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.680164,-91.373413,NaN,NaN,0.570376,-1.594767,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,47.74,27.57,33.227261,-90.257489,0.577952,-1.586082,0.579925,-1.575290,0.000021,0.009246
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,47.78,27.57,33.227391,-90.257533,0.577955,-1.586080,0.579927,-1.575291,0.000021,0.009244
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,47.80,27.57,33.227521,-90.257576,0.577959,-1.586078,0.579930,-1.575292,0.000021,0.009241
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227651,-90.257619,0.577962,-1.586075,0.579932,-1.575293,0.000021,0.009238
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.227781,-90.257663,0.577968,-1.586073,0.579934,-1.575293,0.000021,0.009235

In [9]:
data['Distance'] = data['c']*6371 # unit for Radius of Earth is km
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,...,GPS Speed,Meso Lat,Meso Lon,P2 Lat Rad,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad,a,c,Distance
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,32.679903,-91.374930,NaN,NaN,0.570372,-1.594793,NaN,NaN,NaN
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,32.679969,-91.374551,NaN,NaN,0.570373,-1.594787,NaN,NaN,NaN
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,32.680034,-91.374171,NaN,NaN,0.570374,-1.594780,NaN,NaN,NaN
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,32.680099,-91.373792,NaN,NaN,0.570375,-1.594774,NaN,NaN,NaN
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,32.680164,-91.373413,NaN,NaN,0.570376,-1.594767,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,...,27.57,33.227261,-90.257489,0.577952,-1.586082,0.579925,-1.575290,0.000021,0.009246,58.906360
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,...,27.57,33.227391,-90.257533,0.577955,-1.586080,0.579927,-1.575291,0.000021,0.009244,58.891560
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,...,27.57,33.227521,-90.257576,0.577959,-1.586078,0.579930,-1.575292,0.000021,0.009241,58.876760
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.227651,-90.257619,0.577962,-1.586075,0.579932,-1.575293,0.000021,0.009238,58.852867
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.227781,-90.257663,0.577968,-1.586073,0.579934,-1.575293,0.000021,0.009235,58.835666

In [10]:
# Bearing Formula

In [11]:
y = np.sin(data['P2 Lon Rad'] - (data['Meso Lon Rad']))*np.cos(data['P2 Lat Rad'])
x = ((np.cos(data['Meso Lat Rad'])*np.sin(data['P2 Lat Rad'])) 
     - (np.sin(data['Meso Lat Rad'])*np.cos(data['P2 Lat Rad'])*np.cos(data['P2 Lon Rad'] - data['Meso Lon Rad'])))
data['Bearing'] = np.arctan2(y, x)
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,...,Meso Lat,Meso Lon,P2 Lat Rad,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad,a,c,Distance,Bearing
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.679903,-91.374930,NaN,NaN,0.570372,-1.594793,NaN,NaN,NaN,NaN
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.679969,-91.374551,NaN,NaN,0.570373,-1.594787,NaN,NaN,NaN,NaN
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.680034,-91.374171,NaN,NaN,0.570374,-1.594780,NaN,NaN,NaN,NaN
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.680099,-91.373792,NaN,NaN,0.570375,-1.594774,NaN,NaN,NaN,NaN
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.680164,-91.373413,NaN,NaN,0.570376,-1.594767,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,...,33.227261,-90.257489,0.577952,-1.586082,0.579925,-1.575290,0.000021,0.009246,58.906360,-1.782916
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,...,33.227391,-90.257533,0.577955,-1.586080,0.579927,-1.575291,0.000021,0.009244,58.891560,-1.782836
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,...,33.227521,-90.257576,0.577959,-1.586078,0.579930,-1.575292,0.000021,0.009241,58.876760,-1.782757
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.227651,-90.257619,0.577962,-1.586075,0.579932,-1.575293,0.000021,0.009238,58.852867,-1.782711
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.227781,-90.257663,0.577968,-1.586073,0.579934,-1.575293,0.000021,0.009235,58.835666,-1.782447

In [12]:
# Convert Bearing into degrees
data['Bearing Degrees'] = (np.rad2deg(data['Bearing']))
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,...,Meso Lon,P2 Lat Rad,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad,a,c,Distance,Bearing,Bearing Degrees
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-91.374930,NaN,NaN,0.570372,-1.594793,NaN,NaN,NaN,NaN,NaN
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-91.374551,NaN,NaN,0.570373,-1.594787,NaN,NaN,NaN,NaN,NaN
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-91.374171,NaN,NaN,0.570374,-1.594780,NaN,NaN,NaN,NaN,NaN
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-91.373792,NaN,NaN,0.570375,-1.594774,NaN,NaN,NaN,NaN,NaN
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-91.373413,NaN,NaN,0.570376,-1.594767,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,...,-90.257489,0.577952,-1.586082,0.579925,-1.575290,0.000021,0.009246,58.906360,-1.782916,-102.153567
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,...,-90.257533,0.577955,-1.586080,0.579927,-1.575291,0.000021,0.009244,58.891560,-1.782836,-102.149001
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,...,-90.257576,0.577959,-1.586078,0.579930,-1.575292,0.000021,0.009241,58.876760,-1.782757,-102.144432
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-90.257619,0.577962,-1.586075,0.579932,-1.575293,0.000021,0.009238,58.852867,-1.782711,-102.141821
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-90.257663,0.577968,-1.586073,0.579934,-1.575293,0.000021,0.009235,58.835666,-1.782447,-102.126675

In [13]:
data[['Meso Lat', 'Meso Lon', 'Latitude', 'Longitude', 'Bearing Degrees']]

       Meso Lat   Meso Lon  Latitude  Longitude  Bearing Degrees
0     32.679903 -91.374930       NaN        NaN              NaN
1     32.679969 -91.374551       NaN        NaN              NaN
2     32.680034 -91.374171       NaN        NaN              NaN
3     32.680099 -91.373792       NaN        NaN              NaN
4     32.680164 -91.373413       NaN        NaN              NaN
...         ...        ...       ...        ...              ...
5275  33.227261 -90.257489   33.1142   -90.8758      -102.153567
5276  33.227391 -90.257533   33.1144   -90.8757      -102.149001
5277  33.227521 -90.257576   33.1146   -90.8756      -102.144432
5278  33.227651 -90.257619   33.1148   -90.8754      -102.141821
5279  33.227781 -90.257663   33.1151   -90.8753      -102.126675

[5280 rows x 5 columns]

In [14]:
data['x'] = data['Distance']*np.sin(data['Bearing'])

In [15]:
data['y'] = data['Distance']*np.cos(data['Bearing'])

In [16]:
data

,Decimal Time,Latitude,Longitude,Fast Temp,Slow Temp,RH Slow,Dew Point,Pressure,Wind Speed,Wind Direction,...,P2 Lon Rad,Meso Lat Rad,Meso Lon Rad,a,c,Distance,Bearing,Bearing Degrees,x,y
0,0.504722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.570372,-1.594793,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.505000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.570373,-1.594787,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.505278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.570374,-1.594780,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.505556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.570375,-1.594774,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.505833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.570376,-1.594767,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5275,1.970000,33.1142,-90.8758,23.456,23.4,86.90,21.110,997.892,8.764,240.88,...,-1.586082,0.579925,-1.575290,0.000021,0.009246,58.906360,-1.782916,-102.153567,-57.586082,-12.401710
5276,1.970278,33.1144,-90.8757,23.454,23.4,86.90,21.110,997.898,9.244,242.04,...,-1.586080,0.579927,-1.575291,0.000021,0.009244,58.891560,-1.782836,-102.149001,-57.572601,-12.394006
5277,1.970556,33.1146,-90.8756,23.454,23.4,86.92,21.114,997.914,9.510,241.88,...,-1.586078,0.579930,-1.575292,0.000021,0.009241,58.876760,-1.782757,-102.144432,-57.559121,-12.386302
5278,1.970833,33.1148,-90.8754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.586075,0.579932,-1.575293,0.000021,0.009238,58.852867,-1.782711,-102.141821,-57.536327,-12.378653
5279,1.971111,33.1151,-90.8753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.586073,0.579934,-1.575293,0.000021,0.009235,58.835666,-1.782447,-102.126675,-57.522779,-12.359829

In [20]:
data.to_csv(path + 'Data/P2/5s_AVG_P2_Final_Data.csv', index = False)